#! /bin/bash

MC=https://launcher.mojang.com/v1/objects/0a269b5f2c5b93b1712d0f5dc43b6182b9ab254e/server.jar
WD=/opt/minecraft

rm -rf $WD
mkdir -p $WD

function debug {
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  echo "$1"
  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}

function heredoc {
cat > $1 <<HEREDOCCONTENT
#! /bin/bash
$2
HEREDOCCONTENT
chmod +x $1
echo $1
}

PID=$(heredoc "$WD/pid" "pgrep $WD/server.jar")
debug "create $PID"

HALT=$(heredoc "$WD/halt" ". $PID | xargs kill -9")
debug "create $HALT"

LAUNCH=$(heredoc "$WD/launch" "/usr/bin/java -Xms14g -Xmx14g -jar $WD/server.jar --nogui")
debug "create $LAUNCH"

SERVICE="/etc/systemd/system/minecraft.service"
rm -rf $SERVICE
debug "create $SERVICE"
cat > $SERVICE <<HEREDOC
[Unit]
Description=Black Mesa Minecraft Server

[Service]
ExecStart=$LAUNCH
ExecStartPost=echo "Black Mesa Minecraft server started."
SuccessExitStatus=143
WorkingDirectory=/opt/minecraft

[Install]
WantedBy=multi-user.target
HEREDOC

chmod +x $SERVICE

cd $WD

debug "get Minecraft server (jar)"
curl -O $MC

debug "generate EULA"
. $LAUNCH

debug "accept EULA"
sed -i s/false/true/ eula.txt

debug "done with init"
